---
- name: Run interfaces healthcheck
  hosts: all
  gather_facts: false
  tasks:
    - name: Run interfaces role
      ansible.builtin.include_role:
        name: network.healthchecks.interfaces
      vars:
        interfaces_health_check:
          name: health_check
          vars:
            details: true
            checks:
              - name: all_operational_state_up
              - name: min_operational_state_up
                min_count: 1
              - name: all_admin_state_up
              - name: min_admin_state_up
                min_count: 1
      register: interfaces_result

    - name: Display interfaces health check results
      ansible.builtin.debug:
        var: interfaces_result.health_checks
