---
- name: IP Reachability healthchecks
  hosts: all
  gather_facts: false
  tasks:
    - name: Run ip_reachability role with explicit count
      ansible.builtin.include_role:
        name: network.healthchecks.ip_reachability
      vars:
        ip_targets:
          - 192.0.2.1
          - 198.51.100.1
        count: 2
      register: result

    - name: Display reachability results with explicit count
      ansible.builtin.debug:
        var: result.health_checks

    - name: Run ip_reachability role with default count
      ansible.builtin.include_role:
        name: network.healthchecks.ip_reachability
      vars:
        ip_targets:
          - 192.0.2.1
          - 198.51.100.1
      register: result2

    - name: Display reachability results with default count
      ansible.builtin.debug:
        var: result2.health_checks
